import Link from "next/link";
import { SiteHeader } from "../../site-header";

const snippet = `try:
    train()
except Exception:
    import pdb
    pdb.post_mortem()`;

export default function PdbPostMortemNote() {
  return <main><SiteHeader /><section className="coding-note-head shell"><div className="paper-breadcrumb"><Link href="/coding-skill">CODING SKILL</Link><span>/</span><span>PDB POST MORTEM</span></div><div className="coding-note-title"><span>SKILL 01 · DEBUGGING</span><h1>异常发生后，<br />直接进入现场。</h1><p><code>pdb.post_mortem()</code> 会在异常发生后进入保存着报错现场的 traceback。无需提前猜测断点位置，就能检查当时的调用栈和局部变量。</p></div></section><section className="coding-note-body shell"><aside className="coding-note-nav"><span>ON THIS PAGE</span><a href="#idea">核心区别</a><a href="#template">复制模板</a><a href="#commands">现场命令</a><a href="#boundary">适用边界</a></aside><article className="coding-note-content"><section id="idea"><span className="record-label">01 · CORE IDEA</span><h2>提前埋点与事后勘察</h2><div className="constraint-grid"><div><b>pdb.set_trace()</b><p>程序正常运行到预先放置的位置时暂停。适合验证某段流程，但需要先猜到问题大概在哪里。</p></div><div><b>pdb.post_mortem()</b><p>异常发生后沿 traceback 回到报错现场。适合偶发错误、深层调用报错，以及不确定该在哪里下断点的情况。</p></div></div></section><section id="template"><span className="record-label">02 · COPY TEMPLATE</span><h2>最小可用模板</h2><pre className="code-block"><code>{snippet}</code></pre><div className="insight"><span>为什么有效</span><p><code>except</code> 捕获异常时，当前异常的 traceback 仍然存在；<code>post_mortem()</code> 利用它启动调试器，因此你看到的是出错那一刻的栈帧与变量。</p></div></section><section id="commands"><span className="record-label">03 · FIELD COMMANDS</span><h2>进入现场后先做什么</h2><div className="table-wrap"><table><thead><tr><th>命令</th><th>作用</th><th>现场用途</th></tr></thead><tbody><tr><td><code>bt</code></td><td>显示完整调用栈</td><td>判断异常从哪条调用链传来</td></tr><tr><td><code>p variable</code></td><td>查看变量或表达式</td><td>检查 shape、dtype、索引与路径</td></tr><tr><td><code>u / d</code></td><td>切换上层 / 下层栈帧</td><td>回到自己的调用代码查看输入来源</td></tr><tr><td><code>l</code></td><td>显示附近源码</td><td>把当前变量与具体代码对上</td></tr><tr><td><code>q</code></td><td>退出调试器</td><td>结束现场检查</td></tr></tbody></table></div></section><section id="boundary"><span className="record-label">04 · BOUNDARY</span><h2>别让调试模板吞掉错误</h2><div className="error-card"><span>IMPORTANT</span><h3>适合本地诊断，不应原样留在正式训练任务里。</h3><p>无人值守训练、CI 或线上服务没有人输入命令，进程可能一直挂住。定位完成后删除包装，或只在明确的 debug 开关下启用。</p></div><pre className="code-block"><code>{`if debug:\n    try:\n        train()\n    except Exception:\n        import pdb\n        pdb.post_mortem()\n        raise\nelse:\n    train()`}</code></pre><p><code>raise</code> 会在退出调试器后重新抛出原异常，让任务仍以失败状态结束，避免日志或调度系统将它误判为成功。</p></section></article></section><footer className="footer shell"><span>不凡天 · CODING SKILL 01</span><Link href="/coding-skill">返回技巧库 ↗</Link></footer></main>;
}
